# Puerto donde se ejecutará el backend
server.port=8080

# Habilitar logs para WebClient (opcional, útil para debug)
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG
